### ISSUE TITLE
Typo in quiz on page /04-fode-2.ipynb

### ISSUE THREAD

**Issue by ccolomb2** [jkitchin/f23-06623#13]
In the first question of the last quiz, I believe there is a ",_" missing when getting the meshgrid. The correct code would be:

a = np.linspace(0, 5, 2)
b = np.linspace(5, 10, 3)
c = np.linspace(10, 15, 5)

A, _ , _ = np.meshgrid(a, b, c)

**Comment by jkitchin** [comment]
hopefully fixed this one.
