### ISSUE TITLE
Rewrite formula in assignment /crst-event.ipynb

### ISSUE THREAD

**Issue by ccolomb2** [jkitchin/f23-06623#16]
Students asked for clarification in the formula for volume, in the first markdown cell. It seems to be not clear that nu is dividing only Fa0 and (1-X) is in the numerator of the denominator.

**Comment by jkitchin** [comment]
It is Fao /nu*(1-X). Like Cao *(1-X).

**Comment by jkitchin** [comment]
It is not ambiguous as written as it follows standard order of operations. For (1-X) to be in the denominator there would have to be parentheses enclosing the entire denominator.
