### ISSUE TITLE
Suggestion for plot in /10-min-max.ipynb

### ISSUE THREAD

**Issue by ccolomb2** [jkitchin/f23-06623#23]
In my opinion, the plot before the PFR example would be more clear if we can see the function too.
I just added x = np.linspace(-10, 40, 1000) to the cell and it does the trick.

I think I also didn't expect to see that, for 50 initial guesses between 0 and 6, the solver would find the maxima at -2.6, 9.9, and 37.9, one time each, instead of finding the maximum nearest to the guess. Is this expected ? Is it a numerical issue?

**Comment by jkitchin** [comment]
thanks for the suggestion. fixed.

that is expected, the function is periodic, and some guesses will take a large step into another period.
