### ISSUE TITLE
Quiz questions in /15-intro-linear-algebra.ipynb

### ISSUE THREAD

**Issue by ccolomb2** [jkitchin/f23-06623#34]
I think there are corrections to be made in the 4th and 5th questions of the second quiz:
1) They say 4 matrices, but there are 3
2) there is a bracket missing to close the second matrix
3) If you paste both in a cell, they give a scalar, so for both the answer would be (1), since "Python would do what we mean".

Also, I don't know if this was on purpose, but many questions of the second quiz are repeated in the final quiz.

**Comment by jkitchin** [comment]
thanks. it turns out the shape of a scalar is (), e.g. it is 0-dimensional. it is ok if the questions are repeated, practice makes perfect!
