### ISSUE TITLE
Quiz questions in /16-linear-algebra.ipynb

### ISSUE THREAD

**Issue by ccolomb2** [jkitchin/f23-06623#35]
The second and third question of the quiz needs fixing as said in issue #34:

They say 4 matrices, but there are 3
There is a bracket missing to close the second matrix
If you paste both in a cell, they give a scalar, so for both the answer would be (), since "Python would do what we mean".

I might be wrong, but in the reduced row echelon form question, I think the second matrix is also in rref:

![Screenshot 2023-10-30 at 11 09 17 AM](https://github.com/jkitchin/f23-06623/assets/120957862/2462d594-f220-4806-8927-346be4bcae07)

**Comment by jkitchin** [comment]
thanks. I decided to remove the rref question.
